<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages [
<!ELEMENT messages (message)*>
<!ELEMENT message (name , website? , comment , date , user_ip? , user_agent? , spam)>
<!ATTLIST message mID ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT spam (#PCDATA)>
<!ELEMENT user_ip (#PCDATA)>
<!ELEMENT user_agent (#PCDATA)>
]>
<messages>
<message mID="m3513261488ad657.65523141"><name>marco</name><website></website><comment>osidhfoisdgsosidhgosd</comment><date>1362256200</date><user_ip>::1</user_ip><user_agent>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/536.26.17 (KHTML, like Gecko) Version/6.0.2 Safari/536.26.17</user_agent><spam>0</spam></message></messages>
